//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Config.InventoryServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/ServerConfig.Models")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventoryServices.IInventory")]
    public interface IInventory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/GetMessage", ReplyAction="http://tempuri.org/IInventory/GetMessageResponse")]
        string GetMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/GetMessage", ReplyAction="http://tempuri.org/IInventory/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/AddItem", ReplyAction="http://tempuri.org/IInventory/AddItemResponse")]
        int AddItem(string name, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/AddItem", ReplyAction="http://tempuri.org/IInventory/AddItemResponse")]
        System.Threading.Tasks.Task<int> AddItemAsync(string name, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/AddQuantity", ReplyAction="http://tempuri.org/IInventory/AddQuantityResponse")]
        int AddQuantity(int itemId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/AddQuantity", ReplyAction="http://tempuri.org/IInventory/AddQuantityResponse")]
        System.Threading.Tasks.Task<int> AddQuantityAsync(int itemId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/SubtractQuantity", ReplyAction="http://tempuri.org/IInventory/SubtractQuantityResponse")]
        int SubtractQuantity(int itemId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/SubtractQuantity", ReplyAction="http://tempuri.org/IInventory/SubtractQuantityResponse")]
        System.Threading.Tasks.Task<int> SubtractQuantityAsync(int itemId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/GetItems", ReplyAction="http://tempuri.org/IInventory/GetItemsResponse")]
        Client_Config.InventoryServices.Item[] GetItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/GetItems", ReplyAction="http://tempuri.org/IInventory/GetItemsResponse")]
        System.Threading.Tasks.Task<Client_Config.InventoryServices.Item[]> GetItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/RemoveItem", ReplyAction="http://tempuri.org/IInventory/RemoveItemResponse")]
        void RemoveItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/RemoveItem", ReplyAction="http://tempuri.org/IInventory/RemoveItemResponse")]
        System.Threading.Tasks.Task RemoveItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbAddItem", ReplyAction="http://tempuri.org/IInventory/DbAddItemResponse")]
        int DbAddItem(string name, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbAddItem", ReplyAction="http://tempuri.org/IInventory/DbAddItemResponse")]
        System.Threading.Tasks.Task<int> DbAddItemAsync(string name, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbAddQuantity", ReplyAction="http://tempuri.org/IInventory/DbAddQuantityResponse")]
        int DbAddQuantity(int itemId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbAddQuantity", ReplyAction="http://tempuri.org/IInventory/DbAddQuantityResponse")]
        System.Threading.Tasks.Task<int> DbAddQuantityAsync(int itemId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbSubtractQuantity", ReplyAction="http://tempuri.org/IInventory/DbSubtractQuantityResponse")]
        int DbSubtractQuantity(int itemId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbSubtractQuantity", ReplyAction="http://tempuri.org/IInventory/DbSubtractQuantityResponse")]
        System.Threading.Tasks.Task<int> DbSubtractQuantityAsync(int itemId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbGetItems", ReplyAction="http://tempuri.org/IInventory/DbGetItemsResponse")]
        Client_Config.InventoryServices.Item[] DbGetItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbGetItems", ReplyAction="http://tempuri.org/IInventory/DbGetItemsResponse")]
        System.Threading.Tasks.Task<Client_Config.InventoryServices.Item[]> DbGetItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbRemoveItem", ReplyAction="http://tempuri.org/IInventory/DbRemoveItemResponse")]
        void DbRemoveItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbRemoveItem", ReplyAction="http://tempuri.org/IInventory/DbRemoveItemResponse")]
        System.Threading.Tasks.Task DbRemoveItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbGetItem", ReplyAction="http://tempuri.org/IInventory/DbGetItemResponse")]
        Client_Config.InventoryServices.Item DbGetItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbGetItem", ReplyAction="http://tempuri.org/IInventory/DbGetItemResponse")]
        System.Threading.Tasks.Task<Client_Config.InventoryServices.Item> DbGetItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbSaveItem", ReplyAction="http://tempuri.org/IInventory/DbSaveItemResponse")]
        void DbSaveItem(Client_Config.InventoryServices.Item newItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbSaveItem", ReplyAction="http://tempuri.org/IInventory/DbSaveItemResponse")]
        System.Threading.Tasks.Task DbSaveItemAsync(Client_Config.InventoryServices.Item newItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbClearItems", ReplyAction="http://tempuri.org/IInventory/DbClearItemsResponse")]
        void DbClearItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventory/DbClearItems", ReplyAction="http://tempuri.org/IInventory/DbClearItemsResponse")]
        System.Threading.Tasks.Task DbClearItemsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInventoryChannel : Client_Config.InventoryServices.IInventory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryClient : System.ServiceModel.ClientBase<Client_Config.InventoryServices.IInventory>, Client_Config.InventoryServices.IInventory {
        
        public InventoryClient() {
        }
        
        public InventoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage() {
            return base.Channel.GetMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync() {
            return base.Channel.GetMessageAsync();
        }
        
        public int AddItem(string name, int quantity) {
            return base.Channel.AddItem(name, quantity);
        }
        
        public System.Threading.Tasks.Task<int> AddItemAsync(string name, int quantity) {
            return base.Channel.AddItemAsync(name, quantity);
        }
        
        public int AddQuantity(int itemId, int quantity) {
            return base.Channel.AddQuantity(itemId, quantity);
        }
        
        public System.Threading.Tasks.Task<int> AddQuantityAsync(int itemId, int quantity) {
            return base.Channel.AddQuantityAsync(itemId, quantity);
        }
        
        public int SubtractQuantity(int itemId, int quantity) {
            return base.Channel.SubtractQuantity(itemId, quantity);
        }
        
        public System.Threading.Tasks.Task<int> SubtractQuantityAsync(int itemId, int quantity) {
            return base.Channel.SubtractQuantityAsync(itemId, quantity);
        }
        
        public Client_Config.InventoryServices.Item[] GetItems() {
            return base.Channel.GetItems();
        }
        
        public System.Threading.Tasks.Task<Client_Config.InventoryServices.Item[]> GetItemsAsync() {
            return base.Channel.GetItemsAsync();
        }
        
        public void RemoveItem(int id) {
            base.Channel.RemoveItem(id);
        }
        
        public System.Threading.Tasks.Task RemoveItemAsync(int id) {
            return base.Channel.RemoveItemAsync(id);
        }
        
        public int DbAddItem(string name, int quantity) {
            return base.Channel.DbAddItem(name, quantity);
        }
        
        public System.Threading.Tasks.Task<int> DbAddItemAsync(string name, int quantity) {
            return base.Channel.DbAddItemAsync(name, quantity);
        }
        
        public int DbAddQuantity(int itemId, int quantity) {
            return base.Channel.DbAddQuantity(itemId, quantity);
        }
        
        public System.Threading.Tasks.Task<int> DbAddQuantityAsync(int itemId, int quantity) {
            return base.Channel.DbAddQuantityAsync(itemId, quantity);
        }
        
        public int DbSubtractQuantity(int itemId, int quantity) {
            return base.Channel.DbSubtractQuantity(itemId, quantity);
        }
        
        public System.Threading.Tasks.Task<int> DbSubtractQuantityAsync(int itemId, int quantity) {
            return base.Channel.DbSubtractQuantityAsync(itemId, quantity);
        }
        
        public Client_Config.InventoryServices.Item[] DbGetItems() {
            return base.Channel.DbGetItems();
        }
        
        public System.Threading.Tasks.Task<Client_Config.InventoryServices.Item[]> DbGetItemsAsync() {
            return base.Channel.DbGetItemsAsync();
        }
        
        public void DbRemoveItem(int id) {
            base.Channel.DbRemoveItem(id);
        }
        
        public System.Threading.Tasks.Task DbRemoveItemAsync(int id) {
            return base.Channel.DbRemoveItemAsync(id);
        }
        
        public Client_Config.InventoryServices.Item DbGetItem(int id) {
            return base.Channel.DbGetItem(id);
        }
        
        public System.Threading.Tasks.Task<Client_Config.InventoryServices.Item> DbGetItemAsync(int id) {
            return base.Channel.DbGetItemAsync(id);
        }
        
        public void DbSaveItem(Client_Config.InventoryServices.Item newItem) {
            base.Channel.DbSaveItem(newItem);
        }
        
        public System.Threading.Tasks.Task DbSaveItemAsync(Client_Config.InventoryServices.Item newItem) {
            return base.Channel.DbSaveItemAsync(newItem);
        }
        
        public void DbClearItems() {
            base.Channel.DbClearItems();
        }
        
        public System.Threading.Tasks.Task DbClearItemsAsync() {
            return base.Channel.DbClearItemsAsync();
        }
    }
}
