//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Data {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Data.Teacher))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.Data.Secretary))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int myNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonName {
            get {
                return this.PersonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonNameField, value) != true)) {
                    this.PersonNameField = value;
                    this.RaisePropertyChanged("PersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int myNumber {
            get {
                return this.myNumberField;
            }
            set {
                if ((this.myNumberField.Equals(value) != true)) {
                    this.myNumberField = value;
                    this.RaisePropertyChanged("myNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Teacher : Client.Data.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeniorityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Seniority {
            get {
                return this.SeniorityField;
            }
            set {
                if ((this.SeniorityField.Equals(value) != true)) {
                    this.SeniorityField = value;
                    this.RaisePropertyChanged("Seniority");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Secretary", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Secretary : Client.Data.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypingSpeedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypingSpeed {
            get {
                return this.TypingSpeedField;
            }
            set {
                if ((this.TypingSpeedField.Equals(value) != true)) {
                    this.TypingSpeedField = value;
                    this.RaisePropertyChanged("TypingSpeed");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Data.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPerson", ReplyAction="http://tempuri.org/IDataService/GetPersonResponse")]
        Client.Data.Person GetPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPerson", ReplyAction="http://tempuri.org/IDataService/GetPersonResponse")]
        System.Threading.Tasks.Task<Client.Data.Person> GetPersonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Swap", ReplyAction="http://tempuri.org/IDataService/SwapResponse")]
        Client.Data.SwapResponse Swap(Client.Data.SwapRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/Swap", ReplyAction="http://tempuri.org/IDataService/SwapResponse")]
        System.Threading.Tasks.Task<Client.Data.SwapResponse> SwapAsync(Client.Data.SwapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllMembers", ReplyAction="http://tempuri.org/IDataService/GetAllMembersResponse")]
        Client.Data.Person[] GetAllMembers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAllMembers", ReplyAction="http://tempuri.org/IDataService/GetAllMembersResponse")]
        System.Threading.Tasks.Task<Client.Data.Person[]> GetAllMembersAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Swap", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SwapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int y;
        
        public SwapRequest() {
        }
        
        public SwapRequest(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SwapResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SwapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int y;
        
        public SwapResponse() {
        }
        
        public SwapResponse(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : Client.Data.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<Client.Data.IDataService>, Client.Data.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.Data.Person GetPerson() {
            return base.Channel.GetPerson();
        }
        
        public System.Threading.Tasks.Task<Client.Data.Person> GetPersonAsync() {
            return base.Channel.GetPersonAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Data.SwapResponse Client.Data.IDataService.Swap(Client.Data.SwapRequest request) {
            return base.Channel.Swap(request);
        }
        
        public void Swap(ref int x, ref int y) {
            Client.Data.SwapRequest inValue = new Client.Data.SwapRequest();
            inValue.x = x;
            inValue.y = y;
            Client.Data.SwapResponse retVal = ((Client.Data.IDataService)(this)).Swap(inValue);
            x = retVal.x;
            y = retVal.y;
        }
        
        public System.Threading.Tasks.Task<Client.Data.SwapResponse> SwapAsync(Client.Data.SwapRequest request) {
            return base.Channel.SwapAsync(request);
        }
        
        public Client.Data.Person[] GetAllMembers() {
            return base.Channel.GetAllMembers();
        }
        
        public System.Threading.Tasks.Task<Client.Data.Person[]> GetAllMembersAsync() {
            return base.Channel.GetAllMembersAsync();
        }
    }
}
