USE [master]
GO

/****** Object:  Database [CarRentalContext]    Script Date: 3/1/2016 10:39:04 AM ******/
CREATE DATABASE [CarRentalContext]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarRentalContext', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CarRentalContext.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CarRentalContext_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CarRentalContext_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CarRentalContext] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarRentalContext].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarRentalContext] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CarRentalContext] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CarRentalContext] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CarRentalContext] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CarRentalContext] SET ARITHABORT OFF 
GO

ALTER DATABASE [CarRentalContext] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CarRentalContext] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarRentalContext] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarRentalContext] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarRentalContext] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CarRentalContext] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CarRentalContext] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarRentalContext] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CarRentalContext] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarRentalContext] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CarRentalContext] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarRentalContext] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarRentalContext] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarRentalContext] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarRentalContext] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarRentalContext] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [CarRentalContext] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarRentalContext] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CarRentalContext] SET  MULTI_USER 
GO

ALTER DATABASE [CarRentalContext] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarRentalContext] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarRentalContext] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarRentalContext] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CarRentalContext] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CarRentalContext] SET  READ_WRITE 
GO

