//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IImpreciseService")]
    public interface IImpreciseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpreciseService/GetAge", ReplyAction="http://tempuri.org/IImpreciseService/GetAgeResponse")]
        int GetAge(System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpreciseService/GetAge", ReplyAction="http://tempuri.org/IImpreciseService/GetAgeResponse")]
        System.Threading.Tasks.Task<int> GetAgeAsync(System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpreciseService/AgeDifference", ReplyAction="http://tempuri.org/IImpreciseService/AgeDifferenceResponse")]
        int AgeDifference(System.DateTime DateA, System.DateTime DateB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpreciseService/AgeDifference", ReplyAction="http://tempuri.org/IImpreciseService/AgeDifferenceResponse")]
        System.Threading.Tasks.Task<int> AgeDifferenceAsync(System.DateTime DateA, System.DateTime DateB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImpreciseServiceChannel : ConsoleApplication2.ServiceReference1.IImpreciseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImpreciseServiceClient : System.ServiceModel.ClientBase<ConsoleApplication2.ServiceReference1.IImpreciseService>, ConsoleApplication2.ServiceReference1.IImpreciseService {
        
        public ImpreciseServiceClient() {
        }
        
        public ImpreciseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImpreciseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImpreciseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImpreciseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetAge(System.DateTime Date) {
            return base.Channel.GetAge(Date);
        }
        
        public System.Threading.Tasks.Task<int> GetAgeAsync(System.DateTime Date) {
            return base.Channel.GetAgeAsync(Date);
        }
        
        public int AgeDifference(System.DateTime DateA, System.DateTime DateB) {
            return base.Channel.AgeDifference(DateA, DateB);
        }
        
        public System.Threading.Tasks.Task<int> AgeDifferenceAsync(System.DateTime DateA, System.DateTime DateB) {
            return base.Channel.AgeDifferenceAsync(DateA, DateB);
        }
    }
}
