// <auto-generated />
namespace CarRental02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class car2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(car2));
        
        string IMigrationMetadata.Id
        {
            get { return "201602230032154_car2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
