//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateSpanClient.PreciseServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PreciseServiceReference.IPreciseService")]
    public interface IPreciseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciseService/GetAge", ReplyAction="http://tempuri.org/IPreciseService/GetAgeResponse")]
        int GetAge(System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciseService/GetAge", ReplyAction="http://tempuri.org/IPreciseService/GetAgeResponse")]
        System.Threading.Tasks.Task<int> GetAgeAsync(System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciseService/AgeDifference", ReplyAction="http://tempuri.org/IPreciseService/AgeDifferenceResponse")]
        int AgeDifference(System.DateTime DateA, System.DateTime DateB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreciseService/AgeDifference", ReplyAction="http://tempuri.org/IPreciseService/AgeDifferenceResponse")]
        System.Threading.Tasks.Task<int> AgeDifferenceAsync(System.DateTime DateA, System.DateTime DateB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPreciseServiceChannel : DateSpanClient.PreciseServiceReference.IPreciseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreciseServiceClient : System.ServiceModel.ClientBase<DateSpanClient.PreciseServiceReference.IPreciseService>, DateSpanClient.PreciseServiceReference.IPreciseService {
        
        public PreciseServiceClient() {
        }
        
        public PreciseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreciseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreciseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreciseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetAge(System.DateTime Date) {
            return base.Channel.GetAge(Date);
        }
        
        public System.Threading.Tasks.Task<int> GetAgeAsync(System.DateTime Date) {
            return base.Channel.GetAgeAsync(Date);
        }
        
        public int AgeDifference(System.DateTime DateA, System.DateTime DateB) {
            return base.Channel.AgeDifference(DateA, DateB);
        }
        
        public System.Threading.Tasks.Task<int> AgeDifferenceAsync(System.DateTime DateA, System.DateTime DateB) {
            return base.Channel.AgeDifferenceAsync(DateA, DateB);
        }
    }
}
